10 RANDOMIZE TIMER
20 SEGREDO = RND(1) * 100
25 PRINT VAL(SEGREDO)
30 PRINT "Tente adivinhar o número (0 a 100)."
40 INPUT "Seu palpite: "; PALPITE
45 PRINT VAL(PALPITE)
50 IF VAL(PALPITE) = VAL(SEGREDO) THEN PRINT "Parabéns, você acertou!"
55 IF VAL(PALPITE) = VAL(SEGREDO) THEN GOTO 90
60 IF VAL(PALPITE) < VAL(SEGREDO) THEN PRINT "O número é MAIOR que "; VAL(PALPITE)
70 IF VAL(PALPITE) > VAL(SEGREDO) THEN PRINT "O número é MENOR que "; VAL(PALPITE)
80 GOTO 40
90 END
