10 RANDOMIZE = TIMER
20 LET chave = RND(1*100)
30 PRINT "Tente adivinhar o número (0 a 100)."
40 INPUT "Seu palpite: "; PALPITE
45 PRINT VAL(PALPITE)
50 IF VAL(PALPITE) = VAL(CHAVE) THEN PRINT "Parabéns, você acertou!"
55 IF VAL(PALPITE) = VAL(CHAVE) THEN GOTO 90
60 IF VAL(PALPITE) < VAL(CHAVE) THEN PRINT "O número é MAIOR que " + PALPITE
70 IF VAL(PALPITE) > VAL(CHAVE) THEN PRINT "O número é MENOR que " + PALPITE
80 GOTO 40
90 END
